# the dash is to say it is a task
# there can be multiple tasks
# dash mean list
# Adam Rhoades

- block:
  - name: make directory
    file:
      path: /tmp/testDirectory
      state: directory
    register: direct
  - name: move directory direct
    copy:
      src: files/AdamText.txt
      dest: "{{direct.path}}"
  - name: install tree
    yum:
      name: tree
      state: present
  - fail:
      msg: ":)"
#-------------------------------------

#-------------------------------------
  rescue: 
  - name: delete
    file:
      path: "{{direct.path}}/AdamText.txt"
      state: absent
  - name: remove tree
    yum:
      name: tree
      state: absent

#  always:
